function CMain(oData){var _bUpdate;var _iCurResource=0;var RESOURCE_TO_LOAD=0;var _iState=STATE_LOADING;var _oData;var _oPreloader;var _oMenu;var _oHelp;var _oGame;var _oCongratulations;this.initContainer=function(){var canvas=document.getElementById("canvas");s_oStage=new createjs.Stage(canvas);createjs.Touch.enable(s_oStage);s_oStage.preventSelection=false;s_bMobile=jQuery.browser.mobile;if(s_bMobile===false){s_oStage.enableMouseOver(20);$('body').on('contextmenu','#canvas',function(e){return false;});}
s_iPrevTime=new Date().getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);if(navigator.userAgent.match(/Windows Phone/i)){DISABLE_SOUND_MOBILE=true;}
s_oSpriteLibrary=new CSpriteLibrary();_oPreloader=new CPreloader();_bUpdate=true;};this.soundLoaded=function(){_iCurResource++;var iPerc=Math.floor(_iCurResource/RESOURCE_TO_LOAD*100);_oPreloader.refreshLoader(iPerc);if(_iCurResource===RESOURCE_TO_LOAD){_oPreloader.unload();if(DISABLE_SOUND_MOBILE===false||s_bMobile===false){s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});}
this.gotoMenu();}};this._initSounds=function(){if(!createjs.Sound.initializeDefaultPlugins()){return;}
if(navigator.userAgent.indexOf("Opera")>0||navigator.userAgent.indexOf("OPR")>0){createjs.Sound.alternateExtensions=["mp3"];createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this));createjs.Sound.registerSound("./sounds/click.ogg","click");createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack");createjs.Sound.registerSound("./sounds/cut.ogg","cut");createjs.Sound.registerSound("./sounds/game_over.ogg","game_over");createjs.Sound.registerSound("./sounds/perfect.ogg","perfect");}else{createjs.Sound.alternateExtensions=["ogg"];createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this));createjs.Sound.registerSound("./sounds/click.mp3","click");createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack");createjs.Sound.registerSound("./sounds/cut.mp3","cut");createjs.Sound.registerSound("./sounds/game_over.mp3","game_over");createjs.Sound.registerSound("./sounds/perfect.mp3","perfect");}
RESOURCE_TO_LOAD+=5;};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_info","./sprites/but_info.png");s_oSpriteLibrary.addSprite("but_restart_small","./sprites/but_restart_small.png");s_oSpriteLibrary.addSprite("but_yes","./sprites/but_yes.png");s_oSpriteLibrary.addSprite("but_home","./sprites/but_home.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_start","./sprites/but_start.png");s_oSpriteLibrary.addSprite("but_no","./sprites/but_no.png");s_oSpriteLibrary.addSprite("but_fullscreen","./sprites/but_fullscreen.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("logo_ctl","./sprites/logo_ctl.png");s_oSpriteLibrary.addSprite("logo_menu","./sprites/logo_menu.png");s_oSpriteLibrary.addSprite("bg_score","./sprites/bg_score.png");s_oSpriteLibrary.addSprite("bg_bestscore","./sprites/bg_bestscore.png");RESOURCE_TO_LOAD+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites();};this._onImagesLoaded=function(){_iCurResource++;var iPerc=Math.floor(_iCurResource/RESOURCE_TO_LOAD*100);_oPreloader.refreshLoader(iPerc);if(_iCurResource===RESOURCE_TO_LOAD){_oPreloader.unload();if(DISABLE_SOUND_MOBILE===false||s_bMobile===false){s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1});}
this.gotoMenu();}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages();};this.preloaderReady=function(){if(DISABLE_SOUND_MOBILE===false||s_bMobile===false){this._initSounds();}
this._loadImages();_bUpdate=true;};this.gotoMenu=function(){_oMenu=new CMenu();_iState=STATE_MENU;};this.gotoGame=function(){_oGame=new CGame(_oData);_iState=STATE_GAME;};this.gotoHelp=function(){_oHelp=new CHelp();_iState=STATE_HELP;};this.gotoCongratulations=function(oResult,iScore){_oCongratulations=new CCongratulations(oResult,iScore);_iState=STATE_MENU;};this.stopUpdate=function(){_bUpdate=false;createjs.Ticker.paused=true;$("#block_game").css("display","block");createjs.Sound.setMute(true);};this.startUpdate=function(){s_iPrevTime=new Date().getTime();_bUpdate=true;createjs.Ticker.paused=false;$("#block_game").css("display","none");if(s_bAudioActive){createjs.Sound.setMute(false);}};this._update=function(event){if(_bUpdate===false){return;}
var iCurTime=new Date().getTime();s_iTimeElaps=iCurTime-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=iCurTime;if(s_iCntTime>=1000){s_iCurFps=s_iCntFps;s_iCntTime-=1000;s_iCntFps=0;}
if(_iState===STATE_GAME){_oGame.update();}
s_oStage.update(event);};s_oMain=this;_oData=oData;this.initContainer();}
var s_bMobile;var s_bAudioActive=true;var s_bFullscreen=false;var s_iCntTime=0;var s_iTimeElaps=0;var s_iPrevTime=0;var s_iCntFps=0;var s_iCurFps=0;var s_oAdsLevel=1;var s_iBestScore;var s_oDrawLayer;var s_oStage;var s_oMain;var s_oSpriteLibrary;var s_oSoundTrack;